# Form implementation generated from reading ui file 'C:\Users\admin\Documents\GitHub\ai-la-trieu-phu\ui\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 603)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget = QtWidgets.QWidget(parent=self.widget_6)
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.push_button_thoat = QtWidgets.QPushButton(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_thoat.setFont(font)
        self.push_button_thoat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_button_thoat.setStyleSheet("QPushButton#push_button_thoat {\n"
"    background-color: #e74c3c; /* Màu đỏ cảnh báo */\n"
"    color: #2ecc71; /* Xanh lá cây tươi */\n"
"    border-radius: 15px;\n"
"    padding: 10px 45px;\n"
"    border: 3px solid #c0392b; /* Viền đậm */\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    letter-spacing: 1px; /* Giãn chữ nhẹ */\n"
"    background-image: url(\"ui/assets/image/exit_icon.png\"); \n"
"    background-repeat: no-repeat;\n"
"    background-position: left 12px center;\n"
"    background-size: 28px 28px;\n"
"    box-shadow: 0px 4px 10px rgba(231, 76, 60, 0.5); /* Đổ bóng màu đỏ */\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"QPushButton#push_button_thoat:hover {\n"
"    background-color: #c0392b;  /* Đỏ đậm hơn khi hover */\n"
"    border: 3px solid #a93226;  \n"
"    box-shadow: 0px 6px 15px rgba(192, 57, 43, 0.7); /* Tăng độ bóng */\n"
"    transform: scale(1.1); /* Phóng to nhẹ */\n"
"}\n"
"\n"
"QPushButton#push_button_thoat:pressed {\n"
"    background-color: #922b21; /* Đỏ tối khi bấm */\n"
"    border: 3px solid #78281f;\n"
"    color: #27ae60; /* Xanh lá đậm hơn khi nhấn */\n"
"    box-shadow: 0px 2px 5px rgba(146, 43, 33, 0.8); /* Giảm bóng */\n"
"    transform: scale(0.9); /* Thu nhỏ nhẹ khi click */\n"
"}\n"
"")
        self.push_button_thoat.setAutoRepeat(False)
        self.push_button_thoat.setAutoExclusive(False)
        self.push_button_thoat.setObjectName("push_button_thoat")
        self.gridLayout_4.addWidget(self.push_button_thoat, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.push_button_bat_dau = QtWidgets.QPushButton(parent=self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_bat_dau.setFont(font)
        self.push_button_bat_dau.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_button_bat_dau.setStyleSheet("QPushButton {\n"
"    border-radius: 15px; /* Bo tròn góc */\n"
"    background-color: #0074cc; /* Màu xanh đậm hơn */\n"
"    color: white; /* Màu chữ trắng rõ ràng */\n"
"    padding: 10px 20px; /* Kích thước lớn hơn để dễ bấm */\n"
"    border: 3px solid #005fa3; /* Viền đậm hơn */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    font-size: 16px; /* Kích thước chữ lớn hơn */\n"
"    text-transform: uppercase; /* Chữ in hoa */\n"
"    letter-spacing: 1px; /* Khoảng cách chữ */\n"
"    transition: all 0.2s ease-in-out; /* Hiệu ứng mượt */\n"
"    box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.3); /* Tạo bóng nhẹ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3; /* Đổi màu khi di chuột */\n"
"    border-color: #004b82;\n"
"    transform: scale(1.05); /* Phóng to nhẹ khi hover */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4); /* Bóng đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004b82; /* Màu tối hơn khi click */\n"
"    border-color: #003a66;\n"
"    transform: scale(0.95); /* Thu nhỏ nhẹ khi nhấn */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5); /* Hiệu ứng nhấn xuống */\n"
"}\n"
"")
        self.push_button_bat_dau.setAutoRepeat(False)
        self.push_button_bat_dau.setAutoExclusive(False)
        self.push_button_bat_dau.setObjectName("push_button_bat_dau")
        self.gridLayout.addWidget(self.push_button_bat_dau, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 1, 1, 1, 1)
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.push_button_cai_dat = QtWidgets.QPushButton(parent=self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_cai_dat.setFont(font)
        self.push_button_cai_dat.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_button_cai_dat.setStyleSheet("QPushButton {\n"
"    border-radius: 15px; /* Bo tròn góc */\n"
"    background-color: #0074cc; /* Màu xanh đậm hơn */\n"
"    color: white; /* Màu chữ trắng rõ ràng */\n"
"    padding: 10px 20px; /* Kích thước lớn hơn để dễ bấm */\n"
"    border: 3px solid #005fa3; /* Viền đậm hơn */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    font-size: 16px; /* Kích thước chữ lớn hơn */\n"
"    text-transform: uppercase; /* Chữ in hoa */\n"
"    letter-spacing: 1px; /* Khoảng cách chữ */\n"
"    transition: all 0.2s ease-in-out; /* Hiệu ứng mượt */\n"
"    box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.3); /* Tạo bóng nhẹ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3; /* Đổi màu khi di chuột */\n"
"    border-color: #004b82;\n"
"    transform: scale(1.05); /* Phóng to nhẹ khi hover */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4); /* Bóng đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004b82; /* Màu tối hơn khi click */\n"
"    border-color: #003a66;\n"
"    transform: scale(0.95); /* Thu nhỏ nhẹ khi nhấn */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5); /* Hiệu ứng nhấn xuống */\n"
"}\n"
"")
        self.push_button_cai_dat.setAutoRepeat(False)
        self.push_button_cai_dat.setAutoExclusive(False)
        self.push_button_cai_dat.setObjectName("push_button_cai_dat")
        self.gridLayout_3.addWidget(self.push_button_cai_dat, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_4, 0, 2, 1, 1)
        self.widget_5 = QtWidgets.QWidget(parent=self.widget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.push_button_lich_su_choi = QtWidgets.QPushButton(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_lich_su_choi.setFont(font)
        self.push_button_lich_su_choi.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.push_button_lich_su_choi.setStyleSheet("QPushButton {\n"
"    border-radius: 15px; /* Bo tròn góc */\n"
"    background-color: #0074cc; /* Màu xanh đậm hơn */\n"
"    color: white; /* Màu chữ trắng rõ ràng */\n"
"    padding: 10px 20px; /* Kích thước lớn hơn để dễ bấm */\n"
"    border: 3px solid #005fa3; /* Viền đậm hơn */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    font-size: 16px; /* Kích thước chữ lớn hơn */\n"
"    text-transform: uppercase; /* Chữ in hoa */\n"
"    letter-spacing: 1px; /* Khoảng cách chữ */\n"
"    transition: all 0.2s ease-in-out; /* Hiệu ứng mượt */\n"
"    box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.3); /* Tạo bóng nhẹ */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005fa3; /* Đổi màu khi di chuột */\n"
"    border-color: #004b82;\n"
"    transform: scale(1.05); /* Phóng to nhẹ khi hover */\n"
"    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.4); /* Bóng đậm hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004b82; /* Màu tối hơn khi click */\n"
"    border-color: #003a66;\n"
"    transform: scale(0.95); /* Thu nhỏ nhẹ khi nhấn */\n"
"    box-shadow: inset 3px 3px 6px rgba(0, 0, 0, 0.5); /* Hiệu ứng nhấn xuống */\n"
"}\n"
"")
        self.push_button_lich_su_choi.setAutoRepeat(False)
        self.push_button_lich_su_choi.setAutoExclusive(False)
        self.push_button_lich_su_choi.setObjectName("push_button_lich_su_choi")
        self.gridLayout_2.addWidget(self.push_button_lich_su_choi, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_5, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_button_thoat.setText(_translate("MainWindow", "THOÁT ⏻"))
        self.push_button_bat_dau.setText(_translate("MainWindow", "BẮT ĐẦU 💲💲"))
        self.push_button_cai_dat.setText(_translate("MainWindow", "CÀI ĐẶT"))
        self.push_button_lich_su_choi.setText(_translate("MainWindow", "LỊCH SỬ CHƠI"))
