# Form implementation generated from reading ui file 'C:\laptrinhc\project_millionair\ui\register.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(817, 657)
        Register.setStyleSheet("\n"
"background-repeat: no-repeat;  /* Không lặp lại ảnh */\n"
"background-position: center;  /* Đưa ảnh về trung tâm */\n"
"background-size: contain;  /* Giữ nguyên tỉ lệ ảnh, không bị méo */\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=Register)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_register_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_register_password.setGeometry(QtCore.QRect(340, 340, 211, 41))
        self.lineEdit_register_password.setStyleSheet("/* QLineEdit - Ô nhập liệu */\n"
"QLineEdit {\n"
"    font-size: 18px;  /* Kích thước chữ */\n"
"    font-weight: bold;\n"
"    color: white;  /* Màu chữ trắng */\n"
"    padding: 8px;\n"
"    border: 3px solid #FFD700;  /* Viền vàng kim */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    background: rgba(0, 0, 50, 0.8);  /* Màu xanh đậm trong suốt */\n"
"    text-align: center;  /* Căn giữa chữ */\n"
"    selection-background-color: #FFD700;  /* Màu nền khi chọn text */\n"
"}\n"
"\n"
"/* Khi nhập vào ô, viền sáng lên */\n"
"QLineEdit:focus {\n"
"    border: 3px solid #00CFFF;  /* Viền phát sáng màu xanh neon */\n"
"    background: rgba(0, 0, 80, 0.9);\n"
"}\n"
"")
        self.lineEdit_register_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_register_password.setObjectName("lineEdit_register_password")
        self.pushButton_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_register.setGeometry(QtCore.QRect(380, 460, 131, 51))
        self.pushButton_register.setStyleSheet("/* QLabel - Tiêu đề User Name, Password */\n"
"QLabel {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #FFD700; /* Vàng nổi bật */\n"
"    text-shadow: 2px 2px 4px #000;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* QLineEdit - Ô nhập username, password */\n"
"QLineEdit {\n"
"    font-size: 16px;\n"
"    padding: 8px;\n"
"    border: 2px solid #0077CC; /* Viền xanh neon */\n"
"    border-radius: 8px;\n"
"    background: rgba(0, 0, 50, 0.8); /* Màu xanh đậm trong suốt */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Khi nhập vào ô, viền sẽ sáng lên */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00CFFF; \n"
"    background: rgba(0, 0, 80, 0.9);\n"
"}\n"
"\n"
"/* QPushButton - Nút Đăng nhập và Đăng ký */\n"
"QPushButton {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    border: 2px solid #FFD700; /* Viền vàng nổi bật */\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #0057D9, stop:1 #002F7A);\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover - Sáng rực hơn khi rê chuột */\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #007AFF, stop:1 #0044AA);\n"
"    border-color: #FFFFFF;\n"
"}\n"
"\n"
"/* Hiệu ứng khi nhấn nút - Làm tối lại để giống hiệu ứng bấm trong game */\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #003C82, stop:1 #001A40);\n"
"    border-color: #FFD700;\n"
"}\n"
"\n"
"")
        self.pushButton_register.setObjectName("pushButton_register")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 330, 201, 51))
        self.label_2.setStyleSheet("/* QLabel - Tiêu đề chính */\n"
"QLabel {\n"
"    font-size: 32px;  /* Tăng kích thước chữ */\n"
"    font-weight: bold;\n"
"    color: #FFD700;  /* Màu vàng kim */\n"
"    text-align: center;  /* Căn giữa chữ */\n"
"    qproperty-alignment: \'AlignCenter\';  /* Đảm bảo căn giữa trong Qt */\n"
"    background: transparent;\n"
"    text-shadow: 4px 4px 8px rgba(0, 0, 0, 0.9);  /* Hiệu ứng đổ bóng nổi bật */\n"
"    border: 3px solid #FFD700;  /* Viền vàng giống khung câu hỏi trong game */\n"
"    border-radius: 15px;  /* Bo góc mềm mại */\n"
"    padding: 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #003366, stop:1 #000F40); /* Gradient xanh đậm */\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEdit_register_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_register_username.setGeometry(QtCore.QRect(340, 250, 211, 41))
        self.lineEdit_register_username.setStyleSheet("/* QLineEdit - Ô nhập liệu */\n"
"QLineEdit {\n"
"    font-size: 18px;  /* Kích thước chữ */\n"
"    font-weight: bold;\n"
"    color: white;  /* Màu chữ trắng */\n"
"    padding: 8px;\n"
"    border: 3px solid #FFD700;  /* Viền vàng kim */\n"
"    border-radius: 10px;  /* Bo góc mềm mại */\n"
"    background: rgba(0, 0, 50, 0.8);  /* Màu xanh đậm trong suốt */\n"
"    text-align: center;  /* Căn giữa chữ */\n"
"    selection-background-color: #FFD700;  /* Màu nền khi chọn text */\n"
"}\n"
"\n"
"/* Khi nhập vào ô, viền sáng lên */\n"
"QLineEdit:focus {\n"
"    border: 3px solid #00CFFF;  /* Viền phát sáng màu xanh neon */\n"
"    background: rgba(0, 0, 80, 0.9);\n"
"}\n"
"")
        self.lineEdit_register_username.setObjectName("lineEdit_register_username")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 140, 281, 71))
        self.label_4.setStyleSheet("/* QLabel - Tiêu đề chính */\n"
"QLabel {\n"
"    font-size: 32px;  /* Tăng kích thước chữ */\n"
"    font-weight: bold;\n"
"    color: #FFD700;  /* Màu vàng kim */\n"
"    text-align: center;  /* Căn giữa chữ */\n"
"    qproperty-alignment: \'AlignCenter\';  /* Đảm bảo căn giữa trong Qt */\n"
"    background: transparent;\n"
"    text-shadow: 4px 4px 8px rgba(0, 0, 0, 0.9);  /* Hiệu ứng đổ bóng nổi bật */\n"
"    border: 3px solid #FFD700;  /* Viền vàng giống khung câu hỏi trong game */\n"
"    border-radius: 15px;  /* Bo góc mềm mại */\n"
"    padding: 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #003366, stop:1 #000F40); /* Gradient xanh đậm */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(110, 240, 201, 51))
        self.label_5.setStyleSheet("/* QLabel - Tiêu đề chính */\n"
"QLabel {\n"
"    font-size: 32px;  /* Tăng kích thước chữ */\n"
"    font-weight: bold;\n"
"    color: #FFD700;  /* Màu vàng kim */\n"
"    text-align: center;  /* Căn giữa chữ */\n"
"    qproperty-alignment: \'AlignCenter\';  /* Đảm bảo căn giữa trong Qt */\n"
"    background: transparent;\n"
"    text-shadow: 4px 4px 8px rgba(0, 0, 0, 0.9);  /* Hiệu ứng đổ bóng nổi bật */\n"
"    border: 3px solid #FFD700;  /* Viền vàng giống khung câu hỏi trong game */\n"
"    border-radius: 15px;  /* Bo góc mềm mại */\n"
"    padding: 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #003366, stop:1 #000F40); /* Gradient xanh đậm */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButton_back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(60, 50, 166, 51))
        self.pushButton_back.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #FFD700; /* Màu vàng */\n"
"    background-color: #003366; /* Xanh đậm */\n"
"    border: 3px solid #FFD700; /* Viền vàng */\n"
"    border-radius: 25px; /* Bo tròn */\n"
"    padding: 10px 20px;\n"
"    min-width: 120px;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 1px;\n"
"    outline: none;\n"
"    transition: all 0.3s ease-in-out;\n"
"}\n"
"\n"
"/* Hiệu ứng hover - Nút sáng lên */\n"
"QPushButton:hover {\n"
"    background-color: #0044aa; /* Xanh sáng hơn */\n"
"    border: 3px solid #FFEE58; /* Viền vàng sáng */\n"
"    box-shadow: 0px 0px 10px rgba(255, 215, 0, 0.8);\n"
"}\n"
"\n"
"/* Hiệu ứng khi nhấn */\n"
"QPushButton:pressed {\n"
"    background-color: #002244; /* Xanh tối */\n"
"    border: 3px solid #FFCC00; /* Viền vàng đậm */\n"
"    box-shadow: 0px 0px 5px rgba(255, 215, 0, 0.5);\n"
"    transform: scale(0.95);\n"
"}\n"
"\n"
"/* Nút bị vô hiệu hóa */\n"
"QPushButton:disabled {\n"
"    background-color: #555555; /* Xám */\n"
"    border: 3px solid #777777;\n"
"    color: #999999;\n"
"}\n"
"")
        self.pushButton_back.setObjectName("pushButton_back")
        Register.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Register)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 21))
        self.menubar.setObjectName("menubar")
        Register.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.pushButton_register.setText(_translate("Register", "Register"))
        self.label_2.setText(_translate("Register", "Password"))
        self.label_4.setText(_translate("Register", "Register Game"))
        self.label_5.setText(_translate("Register", "User Name"))
        self.pushButton_back.setText(_translate("Register", "BACK"))
