# Form implementation generated from reading ui file 'D:\download\project_millionair (1)\project_millionair (1)\project_millionair\ui\startagain.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_startagain(object):
    def setupUi(self, startagain):
        startagain.setObjectName("startagain")
        startagain.resize(690, 365)
        self.centralwidget = QtWidgets.QWidget(parent=startagain)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 60, 591, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #003366, stop:1 #3366CC);\n"
"    color: white;\n"
"    font: bold 18px \"Arial\";\n"
"    padding: 5px;\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 10px;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 190, 591, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lich_su_choi_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lich_su_choi_button.setFont(font)
        self.lich_su_choi_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #003366, stop:1 #3366CC);\n"
"    color: white;\n"
"    font: bold 16px \"Arial\";\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #0055AA, stop:1 #3399FF);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #002244;\n"
"    border: 2px solid #FF8C00;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666;\n"
"    border: 2px solid #999999;\n"
"    color: #CCCCCC;\n"
"}\n"
"")
        self.lich_su_choi_button.setObjectName("lich_su_choi_button")
        self.horizontalLayout.addWidget(self.lich_su_choi_button)
        self.bat_dau_lai_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.bat_dau_lai_button.setFont(font)
        self.bat_dau_lai_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #003366, stop:1 #3366CC);\n"
"    color: white;\n"
"    font: bold 16px \"Arial\";\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #0055AA, stop:1 #3399FF);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #002244;\n"
"    border: 2px solid #FF8C00;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666;\n"
"    border: 2px solid #999999;\n"
"    color: #CCCCCC;\n"
"}\n"
"")
        self.bat_dau_lai_button.setObjectName("bat_dau_lai_button")
        self.horizontalLayout.addWidget(self.bat_dau_lai_button)
        self.man_hinh_chinh_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.man_hinh_chinh_button.setFont(font)
        self.man_hinh_chinh_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.man_hinh_chinh_button.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #003366, stop:1 #3366CC);\n"
"    color: white;\n"
"    font: bold 16px \"Arial\";\n"
"    border: 2px solid #FFD700;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, \n"
"                                      stop:0 #0055AA, stop:1 #3399FF);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #002244;\n"
"    border: 2px solid #FF8C00;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #666666;\n"
"    border: 2px solid #999999;\n"
"    color: #CCCCCC;\n"
"}\n"
"")
        self.man_hinh_chinh_button.setObjectName("man_hinh_chinh_button")
        self.horizontalLayout.addWidget(self.man_hinh_chinh_button)
        startagain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=startagain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        startagain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=startagain)
        self.statusbar.setObjectName("statusbar")
        startagain.setStatusBar(self.statusbar)

        self.retranslateUi(startagain)
        QtCore.QMetaObject.connectSlotsByName(startagain)

    def retranslateUi(self, startagain):
        _translate = QtCore.QCoreApplication.translate
        startagain.setWindowTitle(_translate("startagain", "startagain"))
        self.label.setText(_translate("startagain", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Bạn có muốn bắt đầu lại trò chơi không?</span></p></body></html>"))
        self.lich_su_choi_button.setText(_translate("startagain", "Xem lịch sử chơi"))
        self.bat_dau_lai_button.setText(_translate("startagain", "Bắt đầu lại"))
        self.man_hinh_chinh_button.setText(_translate("startagain", "Quay về màn hình chính"))
